import type { CSSProperties } from "react";

export const capabilityStyles = {
  metadataShell: {
    display: "flex",
    flex: "1 1 auto",
    flexDirection: "column",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    width: "100%",
  } satisfies CSSProperties,
  dialogBody: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: "0.75rem",
  } satisfies CSSProperties,
  readyTitle: {
    fontSize: "1.2rem",
    fontWeight: 700,
    color: "#0f172a",
  } satisfies CSSProperties,
  primaryButton: {
    padding: ".5rem 1rem",
    cursor: "pointer",
    height: "2.5rem",
    minWidth: "10rem",
    borderRadius: "0.5rem",
    fontWeight: 600,
    border: "1px solid var(--primary-color-light)",
    backgroundColor: "var(--primary-color-light)",
    color: "var(--background-color-light)",
  } satisfies CSSProperties,
  notice: (kind: "info" | "error"): CSSProperties => ({
    display: "block",
    padding: "0.625rem 0.75rem",
    borderRadius: "0.625rem",
    maxWidth: "100%",
    width: "fit-content",
    font: "500 0.875rem/1.45 var(--font-family, system-ui)",
    textAlign: "center",
    background: kind === "error" ? "#fdecea" : "#edf6ff",
    color: kind === "error" ? "#7a1c1c" : "#1f2937",
  }),
  recordWrap: {
    position: "relative",
    width: "100%",
  } satisfies CSSProperties,
  recordTitle: {
    position: "absolute",
    left: "50%",
    transform: "translate(-50%, -70%)",
    top: 0,
    border: "none",
    background: "transparent",
    color: "#0f172a",
    fontWeight: 700,
    fontSize: "1.8rem",
    pointerEvents: "none",
  } satisfies CSSProperties,
  recordContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "1rem",
    marginTop: "3rem",
    width: "100%",
    paddingBottom: "1rem",
  } satisfies CSSProperties,
  recordGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "0.75rem",
  } satisfies CSSProperties,
  recordTile: {
    border: "0.0625rem solid rgba(0,0,0,0.10)",
    borderRadius: "0.625rem",
    background: "#fbfdff",
    padding: "0.625rem 0.75rem",
  } satisfies CSSProperties,
  recordLabel: {
    font: "600 0.75rem/1.2 var(--font-family, system-ui)",
    color: "#6b7280",
    textTransform: "uppercase",
    letterSpacing: ".02em",
    marginBottom: "0.375rem",
  } satisfies CSSProperties,
  recordValue: {
    font: "600 0.9375rem/1.3 var(--font-family, system-ui)",
    color: "#0f172a",
    wordBreak: "break-word",
  } satisfies CSSProperties,
  recordActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.625rem",
    marginTop: "0.875rem",
    flexWrap: "wrap",
    borderTop: "0.0625rem solid rgba(0,0,0,0.10)",
    width: "100%",
    paddingTop: "1rem",
  } satisfies CSSProperties,
  linkAction: (disabled: boolean): CSSProperties => ({
    fontSize: "0.9375rem",
    color: "#008ba3",
    textDecoration: "none",
    fontWeight: 700,
    cursor: disabled ? "default" : "pointer",
    opacity: disabled ? 0.55 : 1,
    pointerEvents: disabled ? "none" : undefined,
  }),
};
