import type { CSSProperties } from "react";

export const capabilityStyles = {
  batchActions: {
    boxSizing: "border-box",
    display: "grid",
    gap: "0.75rem",
    justifyItems: "center",
    margin: "0 auto",
    maxWidth: "32rem",
    padding: "0.75rem var(--panel-content-padding) var(--panel-content-padding)",
    width: "100%",
  } satisfies CSSProperties,
  composition: {
    boxSizing: "border-box",
    color: "var(--title-ink)",
    display: "flex",
    flex: "1 1 auto",
    flexDirection: "column",
    fontFamily: "var(--font-ui)",
    gap: 0,
    minHeight: 0,
    overflow: "hidden",
    padding: "0.75rem 0 0",
    width: "100%",
  } satisfies CSSProperties,
  compositionAccordion: {
    display: "flex",
    flex: "0 1 auto",
    flexDirection: "column",
    gap: "0.75rem",
    minHeight: 0,
    overflowX: "hidden",
    overflowY: "auto",
    padding: "0 var(--panel-content-padding)",
  } satisfies CSSProperties,
  disabled: {
    cursor: "not-allowed",
    opacity: 0.45,
  } satisfies CSSProperties,
  metadataShell: {
    display: "flex",
    flex: "1 1 auto",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    width: "100%",
  } satisfies CSSProperties,
  readyPanel: {
    display: "grid",
    gap: "0.75rem",
    minHeight: 0,
    width: "100%",
  } satisfies CSSProperties,
  readyActions: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "0.75rem",
    justifyContent: "center",
  } satisfies CSSProperties,
  computeActions: {
    alignItems: "center",
    display: "flex",
    justifyContent: "center",
    marginTop: "0.75rem",
  } satisfies CSSProperties,
  primaryButton: {
    padding: "0.5rem 1rem",
    cursor: "pointer",
    minHeight: "2.75rem",
    minWidth: "10rem",
    borderRadius: "var(--radius-control)",
    fontWeight: 600,
    border: "1px solid var(--primary)",
    backgroundColor: "var(--primary-dark)",
    boxShadow: "var(--shadow-action)",
    color: "var(--white)",
  } satisfies CSSProperties,
  notice: (kind: "info" | "error"): CSSProperties => ({
    display: "block",
    padding: "0.625rem 0.75rem",
    borderRadius: "var(--radius-card)",
    maxWidth: "100%",
    width: "fit-content",
    font: "500 0.875rem/1.45 var(--font-ui)",
    textAlign: "center",
    background: kind === "error" ? "#FEF2F2" : "var(--accent-surface)",
    color: kind === "error" ? "#991B1B" : "var(--body-ink)",
  }),
  recordWrap: {
    display: "grid",
    gap: "0.75rem",
    minHeight: 0,
    width: "100%",
  } satisfies CSSProperties,
  recordActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.625rem",
    flexWrap: "wrap",
    width: "100%",
    paddingTop: "0.25rem",
  } satisfies CSSProperties,
};
